package com.affilemanager.app.ui.localization

/** English is the canonical public UI; Lithuanian source copy is retained as the second locale. */
object UiTranslator {
    private val english = mapOf(
        "Failai" to "Files",
        "Analizė" to "Analyze",
        "Ryšiai" to "Connections",
        "Daugiau" to "More",
        "Uždaryti" to "Close",
        "Atšaukti" to "Cancel",
        "Išsaugoti" to "Save",
        "Pašalinti" to "Remove",
        "Ištrinti" to "Delete",
        "Atidaryti" to "Open",
        "Atnaujinti" to "Refresh",
        "Aukštyn" to "Up",
        "Pasirinkti" to "Select",
        "Pasirinkti visus" to "Select all",
        "Atžymėti visus" to "Deselect all",
        "Kopijuoti" to "Copy",
        "Perkelti" to "Move",
        "Pervadinti" to "Rename",
        "Kurti" to "Create",
        "Sukurti" to "Create",
        "Diegti" to "Install",
        "Vėliau" to "Later",
        "Atsisiųsti" to "Download",
        "Bandyti dar kartą" to "Try again",
        "Tęsti" to "Resume",
        "Pauzė" to "Pause",
        "Atrakinti" to "Unlock",
        "Atstatyti" to "Reset",
        "Taikyti" to "Apply",
        "Ieškoti" to "Search",
        "Paslėpti" to "Hide",
        "Dalintis" to "Share",
        "Eksportuoti" to "Export",
        "Importuoti JSON" to "Import JSON",
        "Aplankas" to "Folder",
        "Aplanką" to "Folder",
        "Failas" to "File",
        "Failą" to "File",
        "Nežinomas" to "Unknown",
        "Neprieinama" to "Unavailable",
        "Įjungtas" to "Enabled",
        "Išjungtas" to "Disabled",
        "Išjungta" to "Off",
        "Pradžia" to "Start",
        "Peržiūra" to "Preview",
        "Pavadinimas" to "Name",
        "Vieta" to "Location",
        "Dydis" to "Size",
        "Pakeista" to "Modified",
        "Skaitomas" to "Readable",
        "Versija" to "Version",
        "Taip" to "Yes",
        "Ne" to "No",
        "Shizuku" to "Shizuku",
        "Root" to "Root",
        "Naudotojas" to "Username",
        "Serveris" to "Server",
        "Prievadas" to "Port",
        "Slaptažodis" to "Password",
        "Pradinis kelias" to "Initial path",
        "Bendrinimo vardas" to "Share name",
        "Domenas (nebūtinas)" to "Domain (optional)",
        "Jungties pavadinimas" to "Connection name",
        "Jungtis" to "Connect",
        "Atjungti" to "Disconnect",
        "Nauja jungtis" to "New connection",
        "Pridėti jungtį" to "Add connection",
        "Redaguoti jungtį" to "Edit connection",
        "Pašalinti jungtį?" to "Remove connection?",
        "Tinklas ir nuotolinės vietos" to "Network and remote locations",
        "Dar nėra jungčių" to "No connections yet",
        "Pridėkite NAS, serverį arba WebDAV vietą." to "Add a NAS, server, or WebDAV location.",
        "Į serverį" to "To server",
        "Pasirinkti iš telefono" to "Choose from phone",
        "Kopijuoti į serverį" to "Copy to server",
        "Kopijuoti į telefoną" to "Copy to phone",
        "Peržiūrėti čia" to "Preview here",
        "Įklijuoti iš serverio" to "Paste from server",
        "Kurti vietinį aplanką" to "Create local folder",
        "Kurti nuotolinį aplanką" to "Create remote folder",
        "Įkelti" to "Upload",
        "Konfliktas" to "Conflict",
        "Praleisti" to "Skip",
        "Kopijuoti į aktyvų vietinį aplanką" to "Copy to active local folder",
        "Sinchronizuoti" to "Sync",
        "Sukurti aplanką" to "Create folder",
        "Ištrinti pasirinktus elementus?" to "Delete selected items?",
        "Ištrinti aplanką ir jo turinį?" to "Delete the folder and its contents?",
        "Ištrinti failą?" to "Delete the file?",
        "Aplankų sinchronizavimas" to "Folder synchronization",
        "Kryptis" to "Direction",
        "Konfliktai" to "Conflicts",
        "Fono tvarkaraštis" to "Background schedule",
        "Išsaugoti tvarkaraštį" to "Save schedule",
        "Peržiūrėti planą" to "Preview plan",
        "Vykdyti planą" to "Run plan",
        "Vietinis → serveris" to "Local → server",
        "Serveris → vietinis" to "Server → local",
        "Abiem kryptimis" to "Both directions",
        "Tik pranešti" to "Report only",
        "Naujesnis laimi" to "Newest wins",
        "Vietinis laimi" to "Local wins",
        "Nuotolinis laimi" to "Remote wins",
        "Palikti abi versijas" to "Keep both versions",
        "Tik nematuojamas tinklas (Wi‑Fi / Ethernet)" to "Unmetered network only (Wi‑Fi / Ethernet)",
        "Kas savaitę" to "Weekly",
        "Naudoti privatų SSH raktą" to "Use a private SSH key",
        "Patikėti pirmą gautą raktą" to "Trust the first received key",
        "SSH rakto SHA256 atspaudas" to "SSH key SHA-256 fingerprint",
        "Naujas slaptažodis (nebūtinas)" to "New password (optional)",
        "Pirmasis raktas bus aiškiai patikėtas" to "The first key will be trusted explicitly",
        "Raktas bus įrašytas ir vėliau pasikeitęs bus blokuojamas." to "The key will be stored and any later change will be blocked.",
        "Raktas bus užšifruotas Android Keystore; slaptažodžio laukas taps rakto slaptafraze." to "The key is encrypted with Android Keystore; the password field becomes the key passphrase.",
        "Palikite slaptažodį ir privataus rakto lauką tuščius, kad išliktų dabartiniai užšifruoti prisijungimo duomenys." to "Leave the password and private-key fields empty to keep the current encrypted credentials.",
        "WebDAV jungiamas tik per HTTPS; peradresavimai su prisijungimu nevykdomi." to "WebDAV uses HTTPS only; authenticated redirects are not followed.",
        "Aktyviame vietiniame aplanke nėra ką kopijuoti." to "There is nothing to copy in the active local folder.",
        "Galima pasirinkti failus ir ištisus aplankus. Esami tokio pat vardo objektai nebus perrašyti." to "You can select files and whole folders. Existing items with the same name will not be overwritten.",
        "Į serverį galima įklijuoti tik nukopijuotus, ne iškirptus elementus" to "Only copied, not cut, items can be pasted to a server",
        "Serverio iškarpinė nebegalioja; prisijunkite prie to paties serverio" to "The server clipboard is no longer valid; connect to the same server",
        "Katalogo atverti nepavyko" to "Could not open the folder",
        "Prieš vykdymą planas apskaičiuojamas dar kartą. Failai tyliai netrinami." to "The plan is recalculated before execution. Files are never deleted silently.",
        "Fone vienu paleidimu leidžiama iki 10 000 veiksmų ir 1 GB; konfliktai bei trynimai nevykdomi tyliai." to "A background run is limited to 10,000 actions and 1 GB; conflicts and deletions never run silently.",
        "Įrankiai ir saugumas" to "Tools and security",
        "Jokių reklamų, sekimo SDK ar privalomos paskyros." to "No ads, tracking SDKs, or mandatory account.",
        "Operacijų centras" to "Operations center",
        "Nėra operacijų" to "No operations",
        "Kopijavimas, archyvavimas ir tinklo perdavimai bus rodomi čia." to "Copy, archive, and network transfers appear here.",
        "Paslėpti užbaigtas" to "Hide completed",
        "Perdavimas kompiuteriui" to "Computer transfer",
        "Veikia" to "Running",
        "Trumpalaikis LAN tinklalapis" to "Temporary LAN web page",
        "Tik vienas pasirinktas katalogas · prisijungimas vienkartiniu kodu · jokio viešo tunelio" to "One selected folder · one-time code · no public tunnel",
        "Kopijuoti adresą" to "Copy address",
        "Sustabdyti" to "Stop",
        "Paleisti" to "Start",
        "Paleidžiama…" to "Starting…",
        "Šiukšliadėžė" to "Trash",
        "Šiukšliadėžė tuščia" to "Trash is empty",
        "Pasirinktos ir debesijos vietos" to "Selected and cloud locations",
        "Fono sinchronizavimas" to "Background synchronization",
        "Atidaryti šiukšliadėžę" to "Open trash",
        "Išvalyti visą šiukšliadėžę" to "Empty trash",
        "Išvalyti visą šiukšliadėžę?" to "Empty all trash?",
        "Išvalyti viską" to "Delete all",
        "Ištrinti visam laikui" to "Delete permanently",
        "Ištrinti visam laikui?" to "Delete permanently?",
        "Ištrinti elementai bus rodomi čia." to "Deleted items appear here.",
        "Šiame kataloge nėra failų." to "There are no files in this folder.",
        "Katalogas tuščias" to "Folder is empty",
        "Atnaujinti šiukšliadėžę" to "Refresh trash",
        "Uždaryti šiukšliadėžę" to "Close trash",
        "Android dokumentų sistema" to "Android document system",
        "Kopijuoti į aktyvų langą" to "Copy to active pane",
        "Kopijuoti pasirinktą vietinį elementą čia" to "Copy the selected local item here",
        "Failų vietos" to "File locations",
        "Tvarkyti pradžios ekraną" to "Customize home",
        "Sekcijų tvarka" to "Section order",
        "Greitųjų vietų nerodoma" to "No quick locations are shown",
        "Perkelti aukštyn" to "Move up",
        "Perkelti žemyn" to "Move down",
        "Pašalinti greitą vietą" to "Remove quick location",
        "Pridėti failo ar aplanko nuorodą" to "Add a file or folder shortcut",
        "Baigti" to "Done",
        "Pridėti greitą vietą" to "Add quick location",
        "Pavadinimas (nebūtina)" to "Name (optional)",
        "Failo arba aplanko kelias" to "File or folder path",
        "Vidinė atmintis" to "Internal storage",
        "Atsisiuntimai" to "Downloads",
        "Dokumentai" to "Documents",
        "Nuotraukos" to "Pictures",
        "Vaizdo įrašai" to "Videos",
        "Muzika" to "Music",
        "Aplankai" to "Folders",
        "Garso failai" to "Audio",
        "Archyvai" to "Archives",
        "Kita" to "Other",
        "Greitos vietos" to "Quick locations",
        "Naujausi failai" to "Recent files",
        "Naujausių failų dar nėra" to "No recent files yet",
        "Rodyti visus" to "View all",
        "Atnaujinti naujausius failus" to "Refresh recent files",
        "Saugyklos" to "Storage",
        "Išimama saugykla" to "Removable storage",
        "Reikia prieigos prie bendrų failų" to "Shared-file access is required",
        "Suteikti" to "Grant access",
        "Be jos programa matys tik sistemos leistas vietas. Android/data vis tiek lieka sistemos ribojamas." to "Without it, the app sees only system-approved locations. Android/data remains restricted by Android.",
        "Nauja kortelė" to "New tab",
        "Uždaryti kortelę" to "Close tab",
        "Dubliuoti kortelę" to "Duplicate tab",
        "Užrakinti kortelę" to "Lock tab",
        "Atrakinti kortelę" to "Unlock tab",
        "Atkurti uždarytą kortelę" to "Restore closed tab",
        "Kortelės veiksmai" to "Tab actions",
        "Sukeisti skydelius" to "Swap panes",
        "Palyginti skydelių aplankus" to "Compare pane folders",
        "Skydelių aplankų palyginimas" to "Pane folder comparison",
        "Skirtumų nerasta" to "No differences found",
        "Tik skirtumai" to "Differences only",
        "Pagal pavadinimą" to "By name",
        "Pagal dydį" to "By size",
        "Pagal datą" to "By date",
        "Pagal tipą" to "By type",
        "Rodyti sąrašą" to "Show list",
        "Rodyti tinklelį" to "Show grid",
        "Rodinio nustatymai" to "Display settings",
        "Greita paieška šiame aplanke" to "Quick search in this folder",
        "Uždaryti greitą paiešką" to "Close quick search",
        "Filtruoti šį aplanką" to "Filter this folder",
        "Atitikmenų nerasta" to "No matches found",
        "Pabandykite kitą pavadinimą" to "Try another name",
        "Išdėstymas" to "Layout",
        "Sąrašas" to "List",
        "Tinklelis" to "Grid",
        "Piktogramų ir aplankų dydis" to "Icon and folder size",
        "Elementų tarpai" to "Item spacing",
        "Tinklelio stulpeliai" to "Grid columns",
        "Rūšiavimas" to "Sorting",
        "Didėjančiai" to "Ascending",
        "Mažėjančiai" to "Descending",
        "Informacija" to "Info",
        "Tipas" to "Type",
        "Prieiga" to "Access",
        "Skaitoma" to "Readable",
        "Rašoma" to "Writable",
        "Kelias" to "Path",
        "Failų miniatiūros" to "File thumbnails",
        "Išsaugoma atskirai šiam katalogui" to "Saved separately for this folder",
        "Rodyti miniatiūras" to "Show thumbnails",
        "Rodyti paslėptus failus" to "Show hidden files",
        "Slėpti paslėptus failus" to "Hide hidden files",
        "Paslėpti failai" to "Hidden files",
        "Čia dar nėra failų" to "No files here yet",
        "Aplankas tuščias" to "Folder is empty",
        "Atidaryti aplanką" to "Open folder",
        "Kraunami duomenys…" to "Loading data…",
        "Aplankas · kraunami duomenys…" to "Folder · loading data…",
        "Įklijuoti" to "Paste",
        "Kopijuoti į kitą skydelį" to "Copy to other pane",
        "Į šiukšlinę" to "Move to trash",
        "Perkelti į šiukšlinę" to "Move to trash",
        "Perkelti į šiukšlinę?" to "Move to trash?",
        "Sukurti archyvą" to "Create archive",
        "Formatas" to "Format",
        "Slaptažodis (nebūtinas, AES-256)" to "Password (optional, AES-256)",
        "Patikimai kopijuoti" to "Reliable copy",
        "Patikimai perkelti" to "Reliable move",
        "Pakeisti esamą" to "Replace existing",
        "Praleisti sutampančius" to "Skip conflicts",
        "Palikti abu" to "Keep both",
        "Patikrinti SHA-256" to "Verify SHA-256",
        "Praleisti klaidingą failą ir tęsti" to "Skip a failed file and continue",
        "Išsaugoti planą ir pradėti" to "Save plan and start",
        "Planas bus išsaugotas prieš vykdymą. Ši taisyklė bus taikoma visiems sutampantiems vardams." to "The plan is saved before execution. This rule applies to all matching names.",
        "Iki 100 klaidų bus palikta galutinėje ataskaitoje" to "Up to 100 errors remain in the final report",
        "Perkėlimas klaidos atveju visada sustoja; nepatikrintas šaltinis nešalinamas." to "A move always stops on error; an unverified source is never removed.",
        "Rekomenduojama: šaltinis šalinamas tik patvirtinus kopiją" to "Recommended: remove the source only after verifying the copy",
        "Lėčiau, bet patvirtina failo turinį" to "Slower, but verifies file contents",
        "Žymos ir istorija" to "Tags and history",
        "Žymos ir įvertinimas" to "Tags and rating",
        "Žymų ir istorijos dar nėra" to "No tags or history yet",
        "Esamos žymos" to "Existing tags",
        "Naujos žymos, atskirtos kableliais" to "New tags, separated by commas",
        "Naujų žymų spalva" to "New-tag color",
        "Įvertinimas (nepasirinkus nekeičiamas)" to "Rating (unchanged when not selected)",
        "Pridėti žymą" to "Add tag",
        "Pašalinti žymą" to "Remove tag",
        "Pašalinti visas" to "Remove all",
        "Pridėti prie mėgstamų" to "Add to favorites",
        "Pašalinti iš mėgstamų" to "Remove from favorites",
        "Paieška ir vietos analizė" to "Search and storage analysis",
        "Analizuoti aplanką" to "Analyze folder",
        "Kur ieškoti" to "Search scope",
        "Šiame aplanke" to "This folder",
        "Visose saugyklose" to "All storage locations",
        "Failų tipai" to "File types",
        "Išplėstiniai filtrai" to "Advanced filters",
        "Visos Android matomos saugyklos" to "All Android-visible storage locations",
        "Reguliarioji išraiška" to "Regular expression",
        "Dydis (MiB)" to "Size (MiB)",
        "Nuo" to "From",
        "Iki" to "To",
        "Senesni nei" to "Older than",
        "Ne senesni nei" to "Not older than",
        "Datos intervalas negalimas" to "Invalid date range",
        "Dydžio ribos netinkamos" to "Invalid size range",
        "Išvalyti filtrus" to "Clear filters",
        "Išsaugoti paiešką" to "Save search",
        "Išsaugotos paieškos" to "Saved searches",
        "Pašalinti išsaugotą paiešką" to "Remove saved search",
        "Paieškos virtualus aplankas" to "Search virtual folder",
        "Dublikatų grupės" to "Duplicate groups",
        "Pasirinkti dublikatų kopijas" to "Select duplicate copies",
        "Pažymėti visas, išskyrus pirmą" to "Select all except the first",
        "Tvarkyti kopijas" to "Manage copies",
        "Perkelti rezultatus į šiukšlinę?" to "Move results to trash?",
        "Programa nieko nepažymi automatiškai. Patikrinkite kelius; pažymėti failai bus perkelti į atkuriamą šiukšlinę." to "The app selects nothing automatically. Check the paths; selected files will move to recoverable trash.",
        "Didžiausi failai" to "Largest files",
        "Didžiausi aplankai" to "Largest folders",
        "Tušti aplankai" to "Empty folders",
        "Failų tipų pasiskirstymas" to "File-type distribution",
        "Atšaukti paskutinį masinį pervadinimą" to "Undo last batch rename",
        "Masinis pervadinimas" to "Batch rename",
        "Rasti pavadinime" to "Find in name",
        "Pakeisti į" to "Replace with",
        "Prefiksas" to "Prefix",
        "Sufiksas" to "Suffix",
        "Pridėti numeravimą" to "Add numbering",
        "Skaitmenys" to "Digits",
        "Raidės" to "Letter case",
        "DIDŽIOSIOS" to "UPPERCASE",
        "mažosios" to "lowercase",
        "Naujas failų plėtinys (nebūtinas)" to "New file extension (optional)",
        "Pakeitimai bus vykdomi tik patvirtinus planą" to "Changes run only after you confirm the plan",
        "Tuščia reikšmė palieka esamą plėtinį; aplankams netaikoma" to "An empty value keeps the current extension; folders are unaffected",
        "Išpakuoti" to "Extract",
        "Išpakuoti archyvą" to "Extract archive",
        "Iššifruoti" to "Decrypt",
        "Iššifruoti šalia originalo" to "Decrypt next to original",
        "Įveskite slaptafrazę" to "Enter passphrase",
        "Slaptažodį palikite tuščią, jei archyvas nešifruotas." to "Leave the password empty if the archive is not encrypted.",
        "Atidaryti su kita programa" to "Open with another app",
        "Atidaryti diegimo lange" to "Open installer",
        "Diegimą visada patvirtina Android sistema. Programa negali jo atlikti tyliai." to "Android always confirms installation. The app cannot install silently.",
        "Failo peržiūros sukurti nepavyko" to "Could not create the file preview",
        "PDF neturi puslapių" to "The PDF has no pages",
        "PDF puslapių skaičius nepalaikomas" to "Unsupported PDF page count",
        "Turinys viršijo 2 MB ribą" to "Content exceeded the 2 MB limit",
        "SHA-256 apskaičiuoti nepavyko" to "Could not calculate SHA-256",
        "Archyvo pradžia" to "Archive root",
        "Grįžti į ankstesnį archyvo aplanką" to "Return to the previous archive folder",
        "Šifruotas AF File Manager failas. Jį galima iššifruoti tik atidarius iš vietinės saugyklos." to "Encrypted AF File Manager file. It can be decrypted only when opened from local storage.",
        "Trukmė" to "Duration",
        "Bitų sparta" to "Bit rate",
        "Parašo SHA-256" to "Signature SHA-256",
        "Įrašomas" to "Installed",
        "Išsaugota" to "Saved",
        "Programų pasirinkiklio atidaryti nepavyko" to "Could not open the app chooser",
        "Programos užraktas" to "App lock",
        "Biometrinis arba įrenginio užraktas" to "Biometric or device lock",
        "Grįžus iš fono failų langas bus užrakintas. Keitimą patvirtina Android." to "The file window locks after returning from the background. Android confirms the change.",
        "Šifruota saugykla" to "Encrypted storage",
        "Pasirinkite failą" to "Select a file",
        "1 failas" to "1 file",
        "AES-256-GCM failų šifravimas" to "AES-256-GCM file encryption",
        "Slaptafrazė neišsaugoma. Originalas automatiškai netrinamas." to "The passphrase is not stored. The original is not deleted automatically.",
        "Šifruoti pasirinktą failą" to "Encrypt selected file",
        "Šifruoti" to "Encrypt",
        "Slaptafrazė" to "Passphrase",
        "Pakartokite" to "Repeat",
        "Mažiausiai 8 ženklai. Pametus slaptafrazę failo atkurti nebus galima." to "At least 8 characters. A lost passphrase cannot be recovered.",
        "Saugūs leidimai iš viešos GitHub repozitorijos" to "Secure releases from the public GitHub repository",
        "Programos atnaujinimas" to "App update",
        "Tikrinti dabar" to "Check now",
        "Tikrinti dar kartą" to "Check again",
        "Tikrinamas naujausias GitHub leidimas…" to "Checking the latest GitHub release…",
        "Atsisiųsti ir patikrinti" to "Download and verify",
        "Bandyti siųsti dar kartą" to "Retry download",
        "Diegimą dar turės patvirtinti Android sistemos lange." to "You still need to confirm installation in Android.",
        "Paleidus programą nauja versija tikrinama ne dažniau kaip kas 6 valandas. APK automatiškai siunčiamas tik nematuojamame tinkle." to "The app checks for a new version at launch at most once every 6 hours. The APK downloads automatically only on an unmetered network.",
        "Vietiniai duomenys lieka įrenginyje" to "Local data stays on the device",
        "Privatumas" to "Privacy",
        "Be reklamų" to "Ad-free",
        "Pažengusio naudotojo režimas" to "Advanced-user mode",
        "Neprivalomas" to "Optional",
        "Aptikta, leidimas dar nesuteiktas" to "Detected; permission not granted",
        "Neįdiegta" to "Not installed",
        "Galimas su dvejetainiu su" to "Available through the su binary",
        "Neaptiktas" to "Not detected",
        "Šis režimas pagal nutylėjimą išjungtas. Jis negali pažadėti prieigos prie Android/data visuose įrenginiuose dėl SELinux ir gamintojo ribojimų." to "This mode is off by default. It cannot promise Android/data access on every device because of SELinux and vendor restrictions.",
        "Pridėti per Android dokumentų sistemą" to "Add through Android's document system",
        "Pašalinti pasirinktą vietą?" to "Remove the selected location?",
        "Pašalinti vietą" to "Remove location",
        "Prisijungimų paslaptys šifruojamos Android Keystore. Analitika ir reklamos SDK nepridėti." to "Connection secrets are encrypted with Android Keystore. No analytics or ad SDKs are included.",
        "Tvarkaraščių nėra" to "No schedules",
        "Prisijunkite skiltyje „Ryšiai“, atidarykite sinchronizavimą ir pasirinkite intervalą." to "Connect under Connections, open synchronization, and choose an interval.",
        "AF File Manager užrakinta" to "AF File Manager is locked",
        "Nauja AF File Manager versija" to "New AF File Manager version",
        "Atnaujinimas paruoštas" to "Update ready",
        "APK SHA-256 ir pasirašymo sertifikatas patikrinti. Diegimą patvirtinsite Android sistemos lange." to "The APK SHA-256 and signing certificate were verified. Confirm installation in Android.",
        "Android nustatymuose leiskite diegti iš šios programos, tada grįžkite ir dar kartą pasirinkite „Diegti“." to "Allow installs from this app in Android settings, then return and select Install again.",
        "Android nustatymuose leiskite diegti iš AF File Manager, grįžkite ir spauskite „Diegti“." to "Allow installs from AF File Manager in Android settings, then return and select Install.",
        "Patvirtinkite tapatybę Android sistemos lange" to "Confirm your identity in the Android system dialog",
        "Įrenginyje nenustatyta tinkama biometrija arba ekrano užraktas" to "No supported biometric or screen lock is configured on this device",
        "Įjungti AF File Manager užraktą" to "Enable AF File Manager lock",
        "Išjungti AF File Manager užraktą" to "Disable AF File Manager lock",
        "Ką daryti" to "What to do",
        "Diagnostikos kodas" to "Diagnostic code",
        "miniatiūra" to "thumbnail",
        "piktograma" to "icon",
        "Rodyti piktogramas" to "Show icons",
        "−" to "−",
        "+" to "+",
        "●" to "●",
        "AES-256-GCM · PBKDF2-HMAC-SHA256" to "AES-256-GCM · PBKDF2-HMAC-SHA256",
        "Aplanko veiksmai" to "Folder actions",
        "Telefonas" to "Phone",
        "Telefono terminalas" to "Phone terminal",
        "Atidaryti terminalą šiame aplanke" to "Open terminal in this folder",
        "Atidaryti serverio terminalą" to "Open server terminal",
        "Kopijuoti pažymėtą tekstą" to "Copy selected text",
        "Slėpti klaviatūrą" to "Hide keyboard",
        "Rodyti klaviatūrą" to "Show keyboard",
        "Uždaryti terminalą" to "Close terminal",
        "Paleidžiamas telefono terminalas…" to "Starting phone terminal…",
        "Jungiamasi prie serverio terminalo…" to "Connecting to server terminal…",
        "Terminalo atidaryti nepavyko" to "Could not open terminal",
        "Terminalo seansas baigtas" to "Terminal session ended",
        "Uždaryti terminalą?" to "Close terminal?",
        "Veikianti komanda bus sustabdyta ir terminalo seansas bus uždarytas." to "The running command will be stopped and the terminal session will close.",
        "Android saugos politika neleido terminalui pasiekti šio aplanko." to "Android security policy denied terminal access to this folder.",
        "Telefono terminalo atidaryti nepavyko." to "Could not open the phone terminal.",
        "Serverio terminalas pasiekiamas tik per SFTP/SSH jungtį" to "A server terminal is available only through an SFTP/SSH connection",
        "Išsaugotas SFTP/SSH profilis nebeegzistuoja" to "The saved SFTP/SSH profile no longer exists",
        "Iškarpinės turinys viršija 64 KiB terminalo įklijavimo ribą" to "Clipboard content exceeds the 64 KiB terminal paste limit",
        "Pažymėtas terminalo tekstas viršija 64 KiB kopijavimo ribą" to "Selected terminal text exceeds the 64 KiB copy limit",
        "Terminalo įvestis užimta; bandykite įklijuoti dar kartą" to "Terminal input is busy; try pasting again",
        "Telefono terminalo atidaryti nepavyko" to "Could not open the phone terminal",
        "Dabartinis aplankas terminalui nepasiekiamas arba nebegalioja." to "The current folder is unavailable to the terminal or no longer exists.",
        "Android terminalo proceso paleisti nepavyko." to "Could not start the Android terminal process.",
        "Atverkite kitą telefono aplanką ir bandykite dar kartą." to "Open another phone folder and try again.",
        "Terminalo ryšys netikėtai nutrūko" to "The terminal connection ended unexpectedly",
        "Terminalo įvesties ryšys netikėtai nutrūko" to "The terminal input connection ended unexpectedly",
        "Terminalo dydžio pakeisti nepavyko" to "Could not resize the terminal",
        "Archyvuoti" to "Archive",
        "Atgal" to "Back",
        "Atitolinti" to "Zoom out",
        "Atšaukti tvarkaraštį" to "Cancel schedule",
        "Bus išsaugotos vietos ir visi dabar pasirinkti filtrai." to "The locations and all currently selected filters will be saved.",
        "Failo arba aplanko pavadinimas" to "File or folder name",
        "Greitas palyginimas pagal pavadinimą, tipą, dydį ir keitimo datą. Failai nekeičiami." to "Quick comparison by name, type, size, and modified date. Files are not changed.",
        "Hierarchija: Projektas/Dokumentai" to "Hierarchy: Project/Documents",
        "Pasirinkite saugyklą arba dažną vietą. Ji bus atverta aktyviame failų skydelyje." to "Choose a storage location or shortcut. It opens in the active file pane.",
        "Paskelbtas naujas stabilus leidimas." to "A new stable release is available.",
        "Pirmyn" to "Forward",
        "Priartinti" to "Zoom in",
        "Regex" to "Regex",
        "Rezultatai sutrumpinti pasiekus 5 000 rezultatų arba 200 000 skenuotų elementų ribą." to "Results were truncated at 5,000 matches or 200,000 scanned items.",
        "Rezultatas sutrumpintas pasiekus saugos ribą" to "The result was truncated at the safety limit",
        "Rikiuoti" to "Sort",
        "Rodinys" to "View",
        "Rodyti aplanke" to "Show in folder",
        "SHA-256" to "SHA-256",
        "Skirtukas" to "Separator",
        "SMB 2/3 · SFTP · WebDAV · FTP/FTPS" to "SMB 2/3 · SFTP · WebDAV · FTP/FTPS",
        "Užrakinta" to "Locked",
        "Veiksmai" to "Actions",
        "Žymos (turi atitikti visas)" to "Tags (must match all)",
        "aktyvus failų langas" to "active file pane",
        "Jungties duomenys neteisingi" to "Invalid connection data",
        "Serverio adresas neteisingas" to "Invalid server address",
        "Android nepavyko rasti nurodyto serverio." to "Android could not resolve the specified server.",
        "Serverio lauke palikite tik IP adresą arba domeną, be prisijungimo duomenų ir ftp://." to "Enter only an IP address or domain in the server field, without credentials or ftp://.",
        "Baigėsi ryšio laukimo laikas" to "Connection timed out",
        "Serveris arba jo duomenų kanalas laiku neatsakė." to "The server or its data channel did not respond in time.",
        "Patikrinkite telefono internetą, prievadą ir serverio pasyvaus FTP prievadus, tada bandykite dar kartą." to "Check the phone connection, port, and the server's passive FTP ports, then try again.",
        "Saugaus ryšio patvirtinti nepavyko" to "Could not verify the secure connection",
        "TLS sertifikatas arba saugaus ryšio suderinimas buvo atmestas." to "The TLS certificate or secure-connection negotiation was rejected.",
        "Patikrinkite, ar pasirinktas FTPS / HTTPS režimas ir ar serverio sertifikatas galioja." to "Check that FTPS or HTTPS is selected and that the server certificate is valid.",
        "FTP serveris uždarė ryšį" to "The FTP server closed the connection",
        "Valdymo ryšys buvo uždarytas prieš užbaigiant komandą." to "The control connection closed before the command completed.",
        "Bandykite dar kartą; jei kartojasi, patikrinkite serverio neveiklumo ir ryšio ribas." to "Try again; if it repeats, check the server's idle and connection limits.",
        "Serverio pasiekti nepavyko" to "Could not reach the server",
        "Nurodytas prievadas nepriėmė ryšio arba iki serverio nėra tinklo kelio." to "The specified port refused the connection or no network route to the server exists.",
        "Patikrinkite IP adresą, prievadą, telefono tinklą ir serverio ugniasienę." to "Check the IP address, port, phone network, and server firewall.",
        "Prisijungimas atmestas" to "Login rejected",
        "Serveris nepriėmė pateiktų prisijungimo duomenų." to "The server rejected the supplied credentials.",
        "Redaguokite jungtį ir patikrinkite naudotojo vardą, slaptažodį bei pasirinktą protokolą." to "Edit the connection and check the username, password, and selected protocol.",
        "Serverio tapatybė nepatvirtinta" to "Server identity not verified",
        "Sertifikatas arba SSH rakto atspaudas neatitiko išsaugotos reikšmės." to "The certificate or SSH-key fingerprint did not match the saved value.",
        "Patikrinkite serverio tapatybę prieš keisdami išsaugotą sertifikatą ar rakto atspaudą." to "Verify the server identity before changing the saved certificate or key fingerprint.",
        "Serveris neleido atlikti veiksmo" to "The server denied the action",
        "Paskyrai nepakanka teisių pasirinktam katalogui arba veiksmui." to "The account lacks permission for the selected folder or action.",
        "Patikrinkite paskyros teises ir pradinį katalogą." to "Check the account permissions and initial folder.",
        "Nuotolinis kelias nepasiekiamas" to "Remote path unavailable",
        "Nurodyto pradinio katalogo arba elemento serveryje nepavyko atverti." to "The specified initial folder or server item could not be opened.",
        "Redaguokite jungtį ir patikrinkite pradinį kelią; dažniausiai tinka /." to "Edit the connection and check the initial path; / is usually correct.",
        "Tinklo ryšys nutrūko" to "Network connection lost",
        "Telefono ir serverio ryšys nutrūko vykdant komandą." to "The connection between the phone and server was lost during the command.",
        "Patikrinkite interneto ryšį ir bandykite dar kartą." to "Check the internet connection and try again.",
        "Prisijungti nepavyko" to "Could not connect",
        "Nuotolinis veiksmas nepavyko" to "Remote action failed",
        "Gauta netikėta ryšio klaida; prisijungimo duomenys saugumo sumetimais nerodomi." to "An unexpected connection error occurred; credentials are hidden for security.",
        "Patikrinkite jungties nustatymus ir pateikite diagnostikos kodą, jei klaida kartojasi." to "Check the connection settings and provide the diagnostic code if the error repeats.",
        "FTP prisijungimas atmestas" to "FTP login rejected",
        "Patikrinkite naudotojo vardą, slaptažodį ir ar reikia FTP, ar FTPS." to "Check the username, password, and whether the server requires FTP or FTPS.",
        "FTP katalogo atverti nepavyko" to "Could not open the FTP folder",
        "Patikrinkite pradinį kelią, paskyros teises ir pasyvaus FTP prievadus." to "Check the initial path, account permissions, and passive FTP ports.",
        "FTP serveris atmetė ryšį" to "The FTP server rejected the connection",
        "Patikrinkite prievadą, serverio apkrovą ir ar pasirinktas tinkamas FTP režimas." to "Check the port, server load, and selected FTP mode.",
        "FTP perdavimo režimas nepalaikomas" to "FTP transfer mode is unsupported",
        "Patikrinkite serverio FTP konfigūraciją arba bandykite kitą protokolą." to "Check the server's FTP configuration or try another protocol.",
        "Sinchronizavimas nepavyko" to "Synchronization failed",
        "Sinchronizavimo plano arba operacijos užbaigti nepavyko." to "The synchronization plan or operation could not be completed.",
        "Patikrinkite abi vietas, ryšį ir bandykite parengti planą dar kartą." to "Check both locations and the connection, then prepare the plan again.",
        "Tik nuotolinis elementas" to "Remote item only",
        "Trūksta vietinio aplanko" to "Local folder is missing",
        "Trūksta vietinio failo" to "Local file is missing",
        "Tik vietinis elementas" to "Local item only",
        "Trūksta nuotolinio aplanko" to "Remote folder is missing",
        "Trūksta nuotolinio failo" to "Remote file is missing",
        "Failo ir aplanko tipai nesutampa" to "File and folder types do not match",
        "Aplankas yra abiejose pusėse" to "Folder exists on both sides",
        "Failai sutampa pagal dydį ir laiką" to "Files match by size and time",
        "Vietinis šaltinis yra autoritetingas" to "The local source is authoritative",
        "Nuotolinis šaltinis yra autoritetingas" to "The remote source is authoritative",
        "Abi versijos skiriasi" to "The two versions differ",
        "Pasirinkta vietinė versija" to "The local version was selected",
        "Pasirinkta nuotolinė versija" to "The remote version was selected",
        "Serveris nepateikė keitimo laiko" to "The server did not provide a modified time",
        "Vietinė versija naujesnė" to "The local version is newer",
        "Nuotolinė versija naujesnė" to "The remote version is newer",
        "Nuotolinė versija paliekama atskiru vardu" to "The remote version is kept under a separate name",
        "Vietinė versija paliekama atskiru vardu" to "The local version is kept under a separate name",
        "Tinklo profilis pašalintas" to "The network profile was removed",
        "Rasta konfliktų; reikia rankinės peržiūros" to "Conflicts were found; manual review is required",
        "Fono veiksmų riba viršyta; paleiskite rankiniu būdu" to "The background action limit was exceeded; run it manually",
        "Fono 1 GB riba viršyta; paleiskite rankiniu būdu" to "The 1 GB background limit was exceeded; run it manually",
        "Įrašykite jungties pavadinimą" to "Enter a connection name",
        "Jungties pavadinimas per ilgas" to "The connection name is too long",
        "Jungties pavadinimas turi būti vienoje eilutėje" to "The connection name must be on one line",
        "Įrašykite serverio IP adresą arba domeną" to "Enter the server IP address or domain",
        "Serverio adresas per ilgas" to "The server address is too long",
        "Serverio lauke palikite tik vieną IP adreso arba domeno eilutę" to "Keep only one IP address or domain line in the server field",
        "Serverio lauke nerašykite ftp:// ar kitos URL schemos" to "Do not enter ftp:// or another URL scheme in the server field",
        "Serverio lauke įrašykite tik IP adresą arba domeną" to "Enter only an IP address or domain in the server field",
        "Prievadą įrašykite atskirame lauke" to "Enter the port in the separate field",
        "Naudotojo vardas per ilgas" to "The username is too long",
        "Naudotojo vardas turi būti vienoje eilutėje" to "The username must be on one line",
        "Pradinis kelias per ilgas" to "The initial path is too long",
        "Pradinis kelias turi būti vienoje eilutėje" to "The initial path must be on one line",
        "Domenas per ilgas" to "The domain is too long",
        "Domenas turi būti vienoje eilutėje" to "The domain must be on one line",
        "Bendrinimo vardas per ilgas" to "The share name is too long",
        "Bendrinimo vardas turi būti vienoje eilutėje" to "The share name must be on one line",
        "Netinkamas prievadas" to "Invalid port",
        "Reikalingas SMB bendrinimo vardas" to "An SMB share name is required",
        "SFTP reikia SHA-256 serverio rakto atspaudo arba aiškaus pirmojo pasitikėjimo" to "SFTP requires a SHA-256 server-key fingerprint or explicit first-use trust",
        "Darbo sesijos išsaugoti nepavyko" to "Could not save the workspace session",
        "Kelias nepasiekiamas" to "Path unavailable",
        "Katalogo vaizdo nustatymo išsaugoti nepavyko" to "Could not save the folder view setting",
        "Kortelių riba pasiekta" to "Tab limit reached",
        "Kortelė užrakinta; pirmiausia ją atrakinkite" to "The tab is locked; unlock it first",
        "Paskutinės skydelio kortelės uždaryti negalima" to "The pane's last tab cannot be closed",
        "Atkuriamų uždarytų kortelių nėra" to "There are no closed tabs to restore",
        "Žymų išsaugoti nepavyko" to "Could not save tags",
        "Žymos pašalintos" to "Tags removed",
        "Žymų pašalinti nepavyko" to "Could not remove tags",
        "Žymų eksportuoti nepavyko" to "Could not export tags",
        "Žymos importuotos" to "Tags imported",
        "Žymų importuoti nepavyko" to "Could not import tags",
        "Žymų perskaityti nepavyko" to "Could not read tags",
        "Patvarus planas išsaugotas ir įtrauktas į operacijų eilę" to "The durable plan was saved and added to the operation queue",
        "Operacijos plano sukurti nepavyko" to "Could not create the operation plan",
        "Keliama į šiukšlinę" to "Moving to trash",
        "Operacijos pradėti nepavyko" to "Could not start the operation",
        "Aplanko sukurti nepavyko" to "Could not create the folder",
        "Failo sukurti nepavyko" to "Could not create the file",
        "Pervadinti nepavyko" to "Could not rename",
        "Pervadinimo pradėti nepavyko" to "Could not start renaming",
        "Atšaukiamas masinis pervadinimas" to "Undoing batch rename",
        "Pervadinimas atšauktas" to "Rename undone",
        "Atšaukimo pradėti nepavyko" to "Could not start undo",
        "Istorijos įrašyti nepavyko" to "Could not record history",
        "Saugyklos perskaityti nepavyko" to "Could not read storage",
        "Archyvo perskaityti nepavyko" to "Could not read the archive",
        "Failo kelias nepateiktas" to "No file path was provided",
        "Failas nepasiekiamas" to "File unavailable",
        "Failo atidaryti nepavyko" to "Could not open the file",
        "Šio tipo nuoroda nepalaikoma" to "This link type is unsupported",
        "Išpakavimo pradėti nepavyko" to "Could not start extraction",
        "Archyvo kūrimo pradėti nepavyko" to "Could not start archive creation",
        "Šifravimo pradėti nepavyko" to "Could not start encryption",
        "Iššifravimo pradėti nepavyko" to "Could not start decryption",
        "Dublikatų kopijos keliamos į šiukšlinę" to "Moving duplicate copies to trash",
        "Dublikatų tvarkymo pradėti nepavyko" to "Could not start duplicate cleanup",
        "Šiukšliadėžė jau tuščia" to "Trash is already empty",
        "Naršymo nustatymų perskaityti nepavyko" to "Could not read navigation settings",
        "Žymos pakeisti nepavyko" to "Could not change the bookmark",
        "Vieta nebeegzistuoja" to "The location no longer exists",
        "Istorijos išvalyti nepavyko" to "Could not clear history",
        "Paieškos išsaugoti nepavyko" to "Could not save the search",
        "Paieškos pašalinti nepavyko" to "Could not remove the search",
        "Programos užraktas įjungtas" to "App lock enabled",
        "Programos užraktas išjungtas" to "App lock disabled",
        "Užrakto nustatymo pakeisti nepavyko" to "Could not change the lock setting",
        "Atkurti nepavyko" to "Could not restore",
        "Ištrinti nepavyko" to "Could not delete",
        "Vietos pridėti nepavyko" to "Could not add the location",
        "Vietos pašalinti nepavyko" to "Could not remove the location",
        "Kopijuojama į Android vietą" to "Copying to an Android location",
        "Kopijuojama iš Android vietos" to "Copying from an Android location",
        "Kopijavimo pradėti nepavyko" to "Could not start copying",
        "Profilių perskaityti nepavyko" to "Could not read profiles",
        "Jungtis atnaujinta" to "Connection updated",
        "Jungtis išsaugota" to "Connection saved",
        "Profilio išsaugoti nepavyko" to "Could not save the profile",
        "Profilio pašalinti nepavyko" to "Could not remove the profile",
        "Nuotolinis ryšys automatiškai atkurtas" to "The remote connection was restored automatically",
        "Atsisiuntimo pradėti nepavyko" to "Could not start the download",
        "Nuotolinio failo atidaryti nepavyko" to "Could not open the remote file",
        "Nuotolinis failas per didelis greitajai peržiūrai. Naudokite „Kopijuoti į telefoną“." to "The remote file is too large for quick preview. Use “Copy to phone”.",
        "Įkėlimo pradėti nepavyko" to "Could not start the upload",
        "Sinchronizuojama" to "Synchronizing",
        "Sinchronizavimo pradėti nepavyko" to "Could not start synchronization",
        "Tvarkaraščių perskaityti nepavyko" to "Could not read schedules",
        "Sinchronizavimo tvarkaraštis išsaugotas" to "Synchronization schedule saved",
        "Tvarkaraščio išsaugoti nepavyko" to "Could not save the schedule",
        "Tvarkaraščio pašalinti nepavyko" to "Could not remove the schedule",
        "Operacijos pakartoti nepavyko" to "Could not retry the operation",
        "Katalogo vaizdo nustatymo perskaityti nepavyko" to "Could not read the folder view setting",
        "Darbo sesijos išsaugojimo eilė nepasiekiama" to "The workspace save queue is unavailable",
        "Veiksmas nepavyko" to "Action failed",
        "Patikimai perkeliama" to "Reliable move",
        "Patikimai kopijuojama" to "Reliable copy",
        "Aplankas abiejose pusėse" to "Folder on both sides",
        "Sutampa dydis ir keitimo data" to "Size and modified date match",
        "Skiriasi tipas, dydis arba keitimo data" to "Type, size, or modified date differs",
        "Tik kairiajame skydelyje" to "Left pane only",
        "Tik dešiniajame skydelyje" to "Right pane only",
        "UTF-8 · iki 2 MB · tik skaityti" to "UTF-8 · up to 2 MB · read-only",
        "UTF-8 · iki 2 MB" to "UTF-8 · up to 2 MB",
        "UTF-8 · iki 2 MB · redaguojama darbinė kopija" to "UTF-8 · up to 2 MB · editable working copy",
        "Įtraukti į iškarpinę" to "Add to clipboard",
        "Kopijuoti daugiau" to "Copy more",
        "Redaguoti su kita programa" to "Edit with another app",
        "Redaguojama kopija dar neparuošta" to "The editable copy is not ready",
        "Nepavyko atidaryti redaktoriaus pasirinkimo" to "Could not open the editor chooser",
        "Ruošiama saugi redaguojama kopija…" to "Preparing a safe editable copy…",
        "Išsaugoma ir patikrinama…" to "Saving and verifying…",
        "Neišsaugoti pakeitimai laikomi privačioje darbinėje kopijoje" to "Unsaved changes are kept in a private working copy",
        "Kopija išsaugota kitur; originalas vis dar skiriasi" to "A copy is saved elsewhere; the original still differs",
        "Redaguojama naudojant privačią darbinę kopiją" to "Editing uses a private working copy",
        "Redagavimo paruošti nepavyko" to "Editing could not be prepared",
        "Išsaugoti kaip" to "Save as",
        "Originalas skirtas tik skaityti. Išsaugokite redaguotą failą kitoje vietoje." to "The original is read-only. Save the edited file to another location.",
        "Atmesti neišsaugotus pakeitimus?" to "Discard unsaved changes?",
        "Redaguojamoje kopijoje yra niekur neišsaugotų pakeitimų. Originalus failas nepakeistas." to "The editable copy has changes that have not been saved anywhere. The original file has not been modified.",
        "Atmesti pakeitimus" to "Discard changes",
        "Tęsti redagavimą" to "Keep editing",
        "Originalus failas pasikeitė" to "The original file changed",
        "AF File Manager jo neperrašė. Palyginkite versijas ir pasirinkite veiksmą." to "AF File Manager did not overwrite it. Compare the revisions and choose what to do.",
        "Originalas atidarymo metu" to "Original when opened",
        "Jūsų redaguojama kopija" to "Your edited copy",
        "Dabartinis originalas" to "Current original",
        "Originalaus failo nebėra" to "The original file no longer exists",
        "Perrašymas pakeis dabartinį originalą. „Išsaugoti kaip“ paliks abi versijas." to "Overwrite replaces the current original. Save as keeps both versions.",
        "Perrašyti originalą" to "Overwrite original",
        "Nepavyko paruošti vidinio redaktoriaus" to "Could not prepare the built-in editor",
        "Paruošta redaguoti" to "Ready to edit",
        "Redaguojama kopija paruošta" to "The editable copy is ready",
        "Išsaugota pradinėje vietoje" to "Saved to the original location",
        "Patikrinta kopija išsaugota pasirinktoje vietoje" to "A verified copy was saved to the selected location",
        "Išsaugota pasirinktoje vietoje" to "Saved to the selected location",
        "Išsaugota pasirinktoje vietoje; tai dabar aktyvus failas" to "Saved to the selected location; this is now the active file",
        "Išorinis redaktorius uždarytas nepakeitus turinio" to "The external editor closed without content changes",
        "Išorinio redaktoriaus pakeitimus galima išsaugoti" to "External editor changes are ready to save",
        "Nepavyko paruošti redaguojamos kopijos" to "Could not prepare an editable copy",
        "Failo išsaugoti nepavyko" to "Could not save the file",
        "Kopijos išsaugoti nepavyko" to "Could not save the copy",
        "Redaguotos kopijos perskaityti nepavyko" to "Could not read the edited copy",
        "Originalas skirtas tik skaityti; naudokite „Išsaugoti kaip“" to "The original is read-only; use Save as",
        "Pasirinkta vieta neįrašoma per Android dokumentų sistemą" to "The selected destination is not writable through Android Documents",
        "Išsaugotos kopijos patikra nepavyko" to "Saved-copy verification failed",
        "Laikinos pradinio failo kopijos pašalinti nepavyko" to "The temporary source copy could not be removed",
        "Laikinos redagavimo kopijos pašalinti nepavyko" to "The temporary editing copy could not be removed",
        "Išsaugoto failo patikra nepavyko" to "Saved-file verification failed",
        "Išsaugoto failo patikrinti nepavyko" to "The saved file could not be verified",
        "Pasirinkta vieta nesuteikė įrašomo srauto" to "The selected location did not provide a writable stream",
        "Serveris negrąžino išsaugoto failo patikrai" to "The server did not return the saved file for verification",
        "Išsaugojimo serveryje patikra nepavyko" to "Server-save verification failed",
        "Pradiniame nuotoliniame kelyje dabar yra aplankas" to "The original remote path now contains a folder",
        "Nuotolinis failas pasikeitė ir dabar yra per didelis saugiai patikrai" to "The remote file changed and is now too large to verify safely",
        "Failas nėra tinkamas UTF-8 tekstas; naudokite kitą redaktorių" to "The file is not valid UTF-8 text; use another editor",
        "Anuliuoti" to "Undo",
        "Pakartoti" to "Redo",
        "Teksto redaktorius" to "Text editor",
        "Rasti ir pakeisti" to "Find and replace",
        "Eiti į eilutę" to "Go to line",
        "Laužyti ilgas eilutes" to "Wrap long lines",
        "Mažinti tekstą" to "Decrease text size",
        "Didinti tekstą" to "Increase text size",
        "Dideliam failui sintaksės spalvinimas išjungtas" to "Syntax highlighting is disabled for this large file",
        "Eilutė" to "Line",
        "Eiti" to "Go",
        "Ankstesnis" to "Previous",
        "Kitas" to "Next",
        "Skirti didžiąsias raides" to "Match case",
        "Visas žodis" to "Whole word",
        "Atitikmens nėra" to "No match",
        "Pakeistas vienas atitikmuo" to "Replaced one match",
        "Pakeisti" to "Replace",
        "Pakeisti visus" to "Replace all",
        "Šiame kataloge nėra poaplankių" to "This folder has no subfolders",
        "Failo pavadinimas" to "File name",
        "Pavadinime negali būti kelio ar valdymo simbolių" to "The name cannot contain path or control characters",
        "Rinktis per Android dokumentų sistemą" to "Choose through Android Documents",
        "Išsaugoti čia" to "Save here",
        "Paskirties failas jau yra" to "The destination file already exists",
        "AF File Manager nieko neperrašė. Pasirinkite, kaip išspręsti konfliktą." to "AF File Manager did not overwrite anything. Choose how to resolve the conflict.",
        "Esamo failo dydis" to "Existing file size",
        "Esamas failas pakeistas" to "Existing file modified",
        "Esamo failo SHA-256" to "Existing file SHA-256",
        "„Perrašyti“ saugiai pakeis esamą failą. „Palikti abu“ parinks laisvą pavadinimą." to "Overwrite safely replaces the existing file. Keep both chooses an available name.",
        "Perrašyti" to "Overwrite",
        "Rinktis kitur" to "Choose another location",
        "Nėra vietinio kopijavimo rinkinio, kurį būtų galima papildyti" to "There is no local copy set to add to",
        "Iškirptų elementų negalima maišyti su „Kopijuoti daugiau“. Pradėkite naują kopijavimo rinkinį." to "Cut items cannot be mixed with Copy more. Start a new copy set.",
        "Nėra serverio kopijavimo rinkinio, kurį būtų galima papildyti" to "There is no server copy set to add to",
        "„Kopijuoti daugiau“ galima tik iš tos pačios serverio jungties" to "Copy more can only add files from the same server connection",
        "→ Nesikeičia" to "→ Unchanged",
        "APK informacija nepasiekiama" to "APK information unavailable",
        "Išvaizda" to "Appearance",
        "Temos režimas" to "Theme mode",
        "Sistema" to "System",
        "Šviesi" to "Light",
        "Tamsi" to "Dark",
        "Spalvų paletė" to "Color palette",
        "Numatytoji" to "Default",
        "Dinaminė" to "Dynamic",
        "Oranžinė" to "Orange",
        "Reikia Android 12+" to "Requires Android 12+",
        "AMOLED juodas režimas" to "AMOLED black mode",
        "Tamsioje temoje fonas tampa visiškai juodas." to "Uses a pure-black background in dark mode.",
        "Išvaizdos nustatymo išsaugoti nepavyko" to "Could not save appearance settings",
        "Naujausių failų įkelti nepavyko" to "Could not load recent files",
        "Naujausių failų įrašo išsaugoti nepavyko" to "Could not save the recent-file entry",
        "Pradžios rodinio nustatymo išsaugoti nepavyko" to "Could not save home display settings",
        "Katalogo vaizdo nustatymo išsaugoti nepavyko" to "Could not save folder display settings",
        "Katalogo vaizdo nustatymo perskaityti nepavyko" to "Could not read folder display settings",
    )

    fun translate(text: String, language: String): String {
        if (language == AppLanguageManager.LITHUANIAN || text.isBlank()) return text
        english[text]?.let { return it }

        if (text.endsWith(" ↑") || text.endsWith(" ↓")) {
            return translate(text.dropLast(2), language) + text.takeLast(2)
        }

        val patterns = listOf(
            Regex("^Eil\\. (\\d+), stulp\\. (\\d+)$") to { match: MatchResult -> "Ln ${match.groupValues[1]}, Col ${match.groupValues[2]}" },
            Regex("^(\\d+) eilučių$") to { match: MatchResult -> "${match.groupValues[1]} lines" },
            Regex("^Pažymėta simbolių: (\\d+)$") to { match: MatchResult -> "${match.groupValues[1]} selected" },
            Regex("^Pakeista: (\\d+)$") to { match: MatchResult -> "Replaced: ${match.groupValues[1]}" },
            Regex("^Išsaugota kaip (.+); tai dabar aktyvus failas$") to { match: MatchResult -> "Saved as ${match.groupValues[1]}; this is now the active file" },
            Regex("^Išsaugota kaip (.+)$") to { match: MatchResult -> "Saved as ${match.groupValues[1]}" },
            Regex("^Prieš išsaugodami pradiniame serveryje vėl prisijunkite prie (.+)$") to { match: MatchResult ->
                "Reconnect to ${match.groupValues[1]} before saving to the original server"
            },
            Regex("^Visi pasirinkti elementai jau buvo iškarpinėje \\((\\d+) iš viso\\)$") to { match: MatchResult ->
                "All selected items were already in the clipboard (${match.groupValues[1]} total)"
            },
            Regex("^Į iškarpinę įtraukta: (\\d+) · iš viso: (\\d+)$") to { match: MatchResult ->
                "Added to clipboard: ${match.groupValues[1]} · total: ${match.groupValues[2]}"
            },
            Regex("^Pasiekta iškarpinės riba: (\\d+) elementų$") to { match: MatchResult ->
                "Clipboard limit reached: ${match.groupValues[1]} items"
            },
            Regex("^Visi pasirinkti serverio elementai jau buvo iškarpinėje \\((\\d+) iš viso\\)$") to { match: MatchResult ->
                "All selected server items were already in the clipboard (${match.groupValues[1]} total)"
            },
            Regex("^Iš serverio įtraukta: (\\d+) · iš viso: (\\d+)$") to { match: MatchResult ->
                "Added from server: ${match.groupValues[1]} · total: ${match.groupValues[2]}"
            },
            Regex("^Pasiekta serverio iškarpinės riba: (\\d+) elementų$") to { match: MatchResult ->
                "Server clipboard limit reached: ${match.groupValues[1]} items"
            },
            Regex("^Pasirinkta: (\\d+)\\. Naujos žymos pridedamos prie esamų; viską pašalina atskiras mygtukas\\.$") to { match: MatchResult ->
                "Selected: ${match.groupValues[1]}. New tags are added to existing ones; use the separate button to remove all."
            },
            Regex("^Pasirinkta: (.+)\\. Failus bus galima atkurti skiltyje „Daugiau“\\.$") to { match: MatchResult ->
                "Selected: ${match.groupValues[1]}. Files can be restored under More."
            },
            Regex("^Pasirinkta: (.+)$") to { match: MatchResult -> "Selected: ${match.groupValues[1]}" },
            Regex("^Kopijuoti \\((\\d+)\\)$") to { match: MatchResult -> "Copy (${match.groupValues[1]})" },
            Regex("^Įklijuoti \\((\\d+)\\)$") to { match: MatchResult -> "Paste (${match.groupValues[1]})" },
            Regex("^Viename skydelyje galima turėti iki (\\d+) kortelių$") to { match: MatchResult -> "A pane can contain up to ${match.groupValues[1]} tabs" },
            Regex("^Žymos išsaugotos (\\d+) elementui\\(-ams\\)$") to { match: MatchResult -> "Tags saved for ${match.groupValues[1]} item(s)" },
            Regex("^Žymos eksportuotos: (.+)$") to { match: MatchResult -> "Tags exported: ${match.groupValues[1]}" },
            Regex("^Paruošta perkelti: (\\d+)$") to { match: MatchResult -> "Ready to move: ${match.groupValues[1]}" },
            Regex("^Nukopijuota į iškarpinę: (\\d+)$") to { match: MatchResult -> "Copied to clipboard: ${match.groupValues[1]}" },
            Regex("^Nukopijuota iš serverio į iškarpinę: (\\d+)$") to { match: MatchResult -> "Copied from server to clipboard: ${match.groupValues[1]}" },
            Regex("^Vienu metu galima pervadinti iki (\\d+) elementų$") to { match: MatchResult -> "You can rename up to ${match.groupValues[1]} items at once" },
            Regex("^Pervadinta: (\\d+)$") to { match: MatchResult -> "Renamed: ${match.groupValues[1]}" },
            Regex("^Pavyko: (\\d+) veiksmų$") to { match: MatchResult -> "Succeeded: ${match.groupValues[1]} actions" },
            Regex("^Nepavyko: (.+)$") to { match: MatchResult -> "Failed: ${translate(match.groupValues[1], language)}" },
            Regex("^Išpakuojamas (.+)$") to { match: MatchResult -> "Extracting ${match.groupValues[1]}" },
            Regex("^Kuriamas (.+)$") to { match: MatchResult -> "Creating ${match.groupValues[1]}" },
            Regex("^Šifruojamas (.+)$") to { match: MatchResult -> "Encrypting ${match.groupValues[1]}" },
            Regex("^Iššifruojamas (.+)$") to { match: MatchResult -> "Decrypting ${match.groupValues[1]}" },
            Regex("^Vienu metu galima tvarkyti iki (.+) dublikatų$") to { match: MatchResult -> "You can process up to ${match.groupValues[1]} duplicates at once" },
            Regex("^Ištrinta: (\\d+), nepavyko ištrinti: (\\d+)$") to { match: MatchResult -> "Deleted: ${match.groupValues[1]}; failed: ${match.groupValues[2]}" },
            Regex("^Šiukšliadėžė išvalyta: (\\d+)$") to { match: MatchResult -> "Trash emptied: ${match.groupValues[1]}" },
            Regex("^Vienu metu galima pasirinkti iki (\\d+) failų ar aplankų$") to { match: MatchResult -> "You can select up to ${match.groupValues[1]} files or folders at once" },
            Regex("^Pasirinkti pirmi (\\d+) elementų$") to { match: MatchResult -> "Selected the first ${match.groupValues[1]} items" },
            Regex("^Kopijuojama iš serverio: (.+)$") to { match: MatchResult -> "Copying from server: ${match.groupValues[1]}" },
            Regex("^Kopijuojama į serverį: (\\d+)$") to { match: MatchResult -> "Copying to server: ${match.groupValues[1]}" },
            Regex("^Nukopijuota į (.+)$") to { match: MatchResult -> "Copied to ${match.groupValues[1]}" },
            Regex("^Serveris atmetė prisijungimą \\(FTP (.+)\\)\\.$") to { match: MatchResult -> "The server rejected the login (FTP ${if (match.groupValues[1] == "be kodo") "no code" else match.groupValues[1]})." },
            Regex("^Prisijungta, bet serveris neatvėrė pradinio katalogo \\(FTP (.+)\\)\\.$") to { match: MatchResult -> "Connected, but the server did not open the initial folder (FTP ${if (match.groupValues[1] == "be kodo") "no code" else match.groupValues[1]})." },
            Regex("^Serverio pradinis atsakymas nebuvo sėkmingas \\(FTP (.+)\\)\\.$") to { match: MatchResult -> "The server greeting was unsuccessful (FTP ${if (match.groupValues[1] == "be kodo") "no code" else match.groupValues[1]})." },
            Regex("^Serveris neįjungė failams būtino dvejetainio režimo \\(FTP (.+)\\)\\.$") to { match: MatchResult -> "The server did not enable the binary mode required for files (FTP ${if (match.groupValues[1] == "be kodo") "no code" else match.groupValues[1]})." },
            Regex("^Pervadinti (\\d+)$") to { match: MatchResult -> "Rename ${match.groupValues[1]}" },
            Regex("^Versija (.+) atsisiųsta ir patikrinta\\.$") to { match: MatchResult -> "Version ${match.groupValues[1]} was downloaded and verified." },
            Regex("^Įdiegta naujausia versija (.+)\\.$") to { match: MatchResult -> "Latest version ${match.groupValues[1]} is installed." },
            Regex("^Galima versija (.+)\\.$") to { match: MatchResult -> "Version ${match.groupValues[1]} is available." },
            Regex("^Versija (.+)$") to { match: MatchResult -> "Version ${match.groupValues[1]}" },
            Regex("^Iš: (.+)$") to { match: MatchResult -> "From: ${match.groupValues[1]}" },
            Regex("^Į: (.+)$") to { match: MatchResult -> "To: ${match.groupValues[1]}" },
            Regex("^Iš serverio → (.+)$") to { match: MatchResult -> "From server → ${match.groupValues[1]}" },
            Regex("^(\\d+) elementai bus ištrinti nuotoliniame serveryje be vietinės šiukšlinės\\.$") to { match: MatchResult ->
                "${match.groupValues[1]} items will be deleted from the remote server without using the local trash."
            },
            Regex("^Iš serverio bus nukopijuota (\\d+) elementų į (.+)\\. Esami vardai nebus perrašyti\\.$") to { match: MatchResult ->
                "${match.groupValues[1]} items will be copied from the server to ${match.groupValues[2]}. Existing names will not be overwritten."
            },
            Regex("^Vietinis: (.+)$") to { match: MatchResult -> "Local: ${match.groupValues[1]}" },
            Regex("^Nuotolinis: (.+)$") to { match: MatchResult -> "Remote: ${match.groupValues[1]}" },
            Regex("^Kairė: (.+)$") to { match: MatchResult -> "Left: ${match.groupValues[1]}" },
            Regex("^Dešinė: (.+)$") to { match: MatchResult -> "Right: ${match.groupValues[1]}" },
            Regex("^Adresas: (.+)$") to { match: MatchResult -> "Address: ${match.groupValues[1]}" },
            Regex("^Katalogas: (.+)$") to { match: MatchResult -> "Folder: ${match.groupValues[1]}" },
            Regex("^Baigsis: (.+)$") to { match: MatchResult -> "Expires: ${match.groupValues[1]}" },
            Regex("^Vienkartinis kodas: (.+)$") to { match: MatchResult -> "One-time code: ${match.groupValues[1]}" },
            Regex("^Rasta (\\d+) failų$") to { match: MatchResult -> "Found ${match.groupValues[1]} files" },
            Regex("^(\\d+) failų$") to { match: MatchResult -> "${match.groupValues[1]} files" },
            Regex("^(\\d+) elementų$") to { match: MatchResult -> "${match.groupValues[1]} items" },
            Regex("^(\\d+) elementų · galima atkurti arba išvalyti viską$") to { match: MatchResult ->
                "${match.groupValues[1]} items · restore them or empty the trash"
            },
            Regex("^(\\d+) dienų$") to { match: MatchResult -> "${match.groupValues[1]} days" },
            Regex("^(\\d+) dienas$") to { match: MatchResult -> "${match.groupValues[1]} days" },
            Regex("^(\\d+) metus$") to { match: MatchResult -> "${match.groupValues[1]} year" },
            Regex("^(.+) laisva iš (.+)$") to { match: MatchResult -> "${match.groupValues[1]} free of ${match.groupValues[2]}" },
            Regex("^(\\d+)% užimta$") to { match: MatchResult -> "${match.groupValues[1]}% used" },
            Regex("^Pažymėta: (\\d+) iš (\\d+)$") to { match: MatchResult -> "Selected: ${match.groupValues[1]} of ${match.groupValues[2]}" },
            Regex("^Keisis (\\d+) / (\\d+)$") to { match: MatchResult -> "Will change ${match.groupValues[1]} / ${match.groupValues[2]}" },
            Regex("^Klaidų: (\\d+)\\. Galima bandyti dar kartą\\.$") to { match: MatchResult -> "Errors: ${match.groupValues[1]}. You can retry." },
            Regex("^Kas (\\d+) val\\. · (tik Wi‑Fi/Ethernet|bet koks tinklas)$") to { match: MatchResult ->
                val network = if (match.groupValues[2] == "tik Wi‑Fi/Ethernet") "Wi-Fi/Ethernet only" else "any network"
                "Every ${match.groupValues[1]} hr · $network"
            },
            Regex("^Kas (\\d+) val\\.(.*)$") to { match: MatchResult -> "Every ${match.groupValues[1]} hr${match.groupValues[2]}" },
            Regex("^Išplėstiniai filtrai · (\\d+)$") to { match: MatchResult -> "Advanced filters · ${match.groupValues[1]}" },
            Regex("^(\\d+) min\\.$") to { match: MatchResult -> "${match.groupValues[1]} min" },
            Regex("^Diagnostikos kodas: (.+)$") to { match: MatchResult -> "Diagnostic code: ${match.groupValues[1]}" },
            Regex("^Ką daryti: (.+)$") to { match: MatchResult -> "What to do: ${translate(match.groupValues[1], language)}" },
            Regex("^Neseniai · (.+)$") to { match: MatchResult -> "Recent · ${match.groupValues[1]}" },
            Regex("^(\\d+) aplankų · (.+)$") to { match: MatchResult -> "${match.groupValues[1]} folders · ${match.groupValues[2]}" },
            Regex("^(.+)/s · liko apie (\\d+)s$") to { match: MatchResult -> "${match.groupValues[1]}/s · about ${match.groupValues[2]}s left" },
            Regex("^(\\d+) vienodi failai · (.+) kiekvienas$") to { match: MatchResult -> "${match.groupValues[1]} identical files · ${match.groupValues[2]} each" },
            Regex("^(.+) · Neteisingi jungties duomenys$") to { match: MatchResult -> "${match.groupValues[1]} · Invalid connection data" },
            Regex("^… ir dar (\\d+)$") to { match: MatchResult -> "… and ${match.groupValues[1]} more" },
            Regex("^(.+) failo tipo piktograma$") to { match: MatchResult -> "${match.groupValues[1]} file-type icon" },
            Regex("^(.+) miniatiūra$") to { match: MatchResult -> "${match.groupValues[1]} thumbnail" },
            Regex("^Aplankas · (.+)$") to { match: MatchResult -> "Folder · ${match.groupValues[1]}" },
            Regex("^Katalogas · (.+)$") to { match: MatchResult -> "Folder · ${match.groupValues[1]}" },
            Regex("^Šiukšliadėžė(.*)$") to { match: MatchResult -> "Trash${match.groupValues[1]}" },
            Regex("^(.+)\\. Paspauskite pieštuką\\.$") to { match: MatchResult -> "${translate(match.groupValues[1], language)}. Tap the pencil icon." },
            Regex("^Atkurti (.+)$") to { match: MatchResult -> "Restore ${match.groupValues[1]}" },
            Regex("^Ištrinti (.+) visam laikui$") to { match: MatchResult -> "Delete ${match.groupValues[1]} permanently" },
            Regex("^Failo veiksmai: (.+)$") to { match: MatchResult -> "File actions: ${match.groupValues[1]}" },
            Regex("^PDF puslapis (\\d+)$") to { match: MatchResult -> "PDF page ${match.groupValues[1]}" },
            Regex("^Dabartinės: (.+)$") to { match: MatchResult -> "Current: ${match.groupValues[1]}" },
            Regex("^Perskaityta (\\d+) elementų · (\\d+) vieta\\(-os\\)$") to { match: MatchResult -> "Scanned ${match.groupValues[1]} items · ${match.groupValues[2]} location(s)" },
            Regex("^Rasta (\\d+) · metaduomenys (\\d+)/(\\d+)$") to { match: MatchResult -> "Found ${match.groupValues[1]} · metadata ${match.groupValues[2]}/${match.groupValues[3]}" },
            Regex("^Planas: (\\d+) veiksmų · (.+) · konfliktų (\\d+)$") to { match: MatchResult -> "Plan: ${match.groupValues[1]} actions · ${match.groupValues[2]} · ${match.groupValues[3]} conflicts" },
            Regex("^Tik skirtumai · (\\d+)$") to { match: MatchResult -> "Differences only · ${match.groupValues[1]}" },
            Regex("^Bus atšauktas AF File Manager ilgalaikis leidimas vietai „(.+)“\\. Failai nebus trinami\\.$") to { match: MatchResult ->
                "AF File Manager's persistent permission for “${match.groupValues[1]}” will be revoked. Files will not be deleted."
            },
            Regex("^Bus bendrinamas aktyvus katalogas: (.+)$") to { match: MatchResult -> "Active folder to share: ${match.groupValues[1]}" },
            Regex("^Bus pašalintas „(.+)“ profilis ir jo užšifruotas prisijungimo įrašas\\.$") to { match: MatchResult ->
                "The “${match.groupValues[1]}” profile and its encrypted credential entry will be removed."
            },
            Regex("^Rodomi pirmi (\\d+) elementų\\. Sąrašas sutrumpintas, failai nepakeisti\\.$") to { match: MatchResult ->
                "Showing the first ${match.groupValues[1]} items. The list is truncated; files were not changed."
            },
            Regex("^Visi (\\d+) šiukšliadėžėje esantys elementai bus ištrinti visam laikui ir jų atkurti nebebus galima\\.$") to { match: MatchResult ->
                "All ${match.groupValues[1]} trash items will be deleted permanently and cannot be restored."
            },
            Regex("^„(.+)“ bus ištrintas nuotoliniame serveryje be vietinės šiukšlinės\\.$") to { match: MatchResult ->
                "“${match.groupValues[1]}” will be deleted on the remote server without local trash."
            },
            Regex("^„(.+)“ nebebus galima atkurti iš programos šiukšliadėžės\\.$") to { match: MatchResult ->
                "“${match.groupValues[1]}” can no longer be restored from the app trash."
            },
            Regex("^„(.+)“ bus trinamas per Android dokumentų teikėją ir nepateks į AF File Manager šiukšlinę\\.$") to { match: MatchResult ->
                "“${match.groupValues[1]}” will be deleted through Android's document provider and will not enter AF File Manager trash."
            },
        )
        patterns.firstNotNullOfOrNull { (pattern, replacement) ->
            pattern.matchEntire(text)?.let(replacement)
        }?.let { return it }

        return text
    }
}
